import { RawMaterial, Recipe, ProductionBatch, PurchaseBill, OrderPlan, SaleEntry, ExpenseEntry, DailyUsageEntry, EmployeeSalary, CompanyInvoiceSettings } from './types';

const RAW_MATERIALS_WITH_COST: RawMaterial[] = [
  {
    id: 'mat_besan',
    name: 'Gram Flour (Besan) / கடலை மாவு',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 10000,
    averageCostPerGram: 0.08,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_rice_flour',
    name: 'Rice Flour / அரிசி மாவு',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 15000,
    averageCostPerGram: 0.05,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_rice_paste',
    name: 'Rice Paste Flour / அரிசி பசை மாவு',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.06,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_tapioca',
    name: 'Tapioca / Potato Flour / கிழங்கு மாவு',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.07,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_peas_flour',
    name: 'Peas Flour / பட்டாணி மாவு',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.08,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_corn_flour',
    name: 'Corn Flour / கான்பிளவர் மாவு',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.06,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_cumin',
    name: 'Cumin Seeds / சீரகம்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.30,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_fennel',
    name: 'Fennel Seeds / சோம்பு',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.25,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_pepper',
    name: 'Pepper / மிளகு',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.60,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_omam',
    name: 'Carom Seeds (Ajwain) / ஓமம்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.28,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_sesame',
    name: 'Black Sesame Seeds / கருப்பு எள்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.22,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_turmeric',
    name: 'Turmeric Powder / மஞ்சள் தூள்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.20,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_chili',
    name: 'Chili Powder / மிளகாய்த்தூள்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.32,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_curry_masala',
    name: 'Curry Masala Powder / கறி மசாலா தூள்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.25,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_garam_masala',
    name: 'Garam Masala Powder / கரம் மசாலாத்தூள்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.30,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_chicken_masala',
    name: 'Chicken Masala Powder / சிக்கன் மசாலா தூள்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.30,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_black_salt',
    name: 'Black Salt / கருப்பு உப்பு',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.08,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_salt',
    name: 'Salt / உப்பு',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 2000,
    averageCostPerGram: 0.02,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_baking_soda',
    name: 'Baking Soda / ஆப்ப சோடா',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.06,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_dalda',
    name: 'Dalda / டால்டா',
    category: 'Dairy',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 2000,
    averageCostPerGram: 0.15,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_green_gram',
    name: 'Green Gram Dal / பச்சை பயறு பருப்பு',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.11,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_masoor_dal',
    name: 'Masoor Dal / மைசூர் பருப்பு',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.10,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_chana_dal',
    name: 'Chana Dal / கடலை பருப்பு',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.09,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_fried_gram',
    name: 'Fried Gram / பொட்டுக்கடலை',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.12,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_peanuts',
    name: 'Peanuts / வேர்க்கடலை',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.14,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_poha',
    name: 'Poha (Beaten Rice) / அவள்',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.06,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_corn',
    name: 'Corn / கான்',
    category: 'Flour',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.05,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_asafoetida',
    name: 'Asafoetida Powder (Hing) / பெருங்காயத்தூள்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 1000,
    averageCostPerGram: 0.40,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_color_yellow_orange',
    name: 'Yellow Orange Food Color / மஞ்சள் ஆரஞ்சு கலர்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 500,
    averageCostPerGram: 0.50,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_color_red_orange',
    name: 'Red Orange Food Color / சிகப்பு ஆரஞ்சு கலர்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 500,
    averageCostPerGram: 0.50,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_color_green',
    name: 'Green Food Color / பச்சை கலர்',
    category: 'Spices',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 500,
    averageCostPerGram: 0.50,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_peas',
    name: 'Peas / பட்டாணி',
    category: 'Other',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.12,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_potato',
    name: 'Potato / உருளைக்கிழங்கு',
    category: 'Other',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 10000,
    averageCostPerGram: 0.04,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_onion',
    name: 'Onion / வெங்காயம்',
    category: 'Other',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 10000,
    averageCostPerGram: 0.035,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_green_chili',
    name: 'Green Chili / பச்சை மிளகாய்',
    category: 'Other',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 3000,
    averageCostPerGram: 0.06,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_garlic',
    name: 'Garlic / பூண்டு',
    category: 'Other',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 3000,
    averageCostPerGram: 0.15,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_ginger',
    name: 'Ginger / இஞ்சி',
    category: 'Other',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 3000,
    averageCostPerGram: 0.12,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_gloves',
    name: 'Gloves / கையுறை',
    category: 'Other',
    unit: 'pcs',
    currentStockGrams: 0,
    minStockGrams: 100,
    averageCostPerGram: 5.0,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_hair_cap',
    name: 'Hair Cap / தலைமாட்டி',
    category: 'Other',
    unit: 'pcs',
    currentStockGrams: 0,
    minStockGrams: 100,
    averageCostPerGram: 3.0,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_soap_powder',
    name: 'Soap Powder / சோப்புத்தூள்',
    category: 'Other',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.08,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_sabena_powder',
    name: 'Sabena Powder / சபீனாத்தூள்',
    category: 'Other',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.05,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_soap_liquid',
    name: 'Soap Liquid / சோப்பு லிக்யூட்',
    category: 'Other',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.10,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_oil',
    name: 'Palm Oil / பாமாயில்',
    category: 'Oil',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 15000,
    averageCostPerGram: 0.12,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_old_oil',
    name: 'Old Palm Oil / old பாமாயில்',
    category: 'Oil',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 5000,
    averageCostPerGram: 0.08,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'mat_butter',
    name: 'Butter / வெண்ணெய்',
    category: 'Dairy',
    unit: 'g',
    currentStockGrams: 0,
    minStockGrams: 2000,
    averageCostPerGram: 0.45,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'pouch_50g',
    name: 'Pouch - 50g Size / பாக்கெட் - 50g',
    category: 'Packaging',
    unit: 'pcs',
    currentStockGrams: 0,
    minStockGrams: 300,
    averageCostPerGram: 1.50,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'pouch_100g',
    name: 'Pouch - 100g Size / பாக்கெட் - 100g',
    category: 'Packaging',
    unit: 'pcs',
    currentStockGrams: 0,
    minStockGrams: 200,
    averageCostPerGram: 2.20,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
  {
    id: 'pouch_250g',
    name: 'Pouch - 250g Size / பாக்கெட் - 250g',
    category: 'Packaging',
    unit: 'pcs',
    currentStockGrams: 0,
    minStockGrams: 150,
    averageCostPerGram: 3.50,
    lastUpdated: '2026-07-19T07:30:00Z',
  },
];

export const INITIAL_RAW_MATERIALS: RawMaterial[] = RAW_MATERIALS_WITH_COST.map(m => ({
  ...m,
  currentStockGrams: 0,
  averageCostPerGram: 0
}));

export const INITIAL_RECIPES: Recipe[] = [];

export const INITIAL_PRODUCTION_BATCHES: ProductionBatch[] = [
  // Cleared to empty list for a 0-value start
];

export const INITIAL_PURCHASE_BILLS: PurchaseBill[] = [
  // Cleared to empty list for a 0-value start
];

export const INITIAL_ORDER_PLANS: OrderPlan[] = [
  // Cleared
];

export const INITIAL_SALES_ENTRIES: SaleEntry[] = [];

export const INITIAL_EXPENSE_ENTRIES: ExpenseEntry[] = [];

export const DEFAULT_ROLE_PERMISSIONS = {
  CEO: {
    canAccessInventory: true,
    canAccessRecipes: true,
    canAccessProduction: true,
    canAccessSales: true,
    canAccessAttendance: true,
    canAccessSalary: true,
    canAccessCostReport: true,
    canAccessAuditLogs: true,
    canAccessExpenses: true,
    canEdit: true,
    canDelete: true,
    canManageRoles: true,
  },
  Manager: {
    canAccessInventory: true,
    canAccessRecipes: true,
    canAccessProduction: true,
    canAccessSales: true,
    canAccessAttendance: true,
    canAccessSalary: true,
    canAccessCostReport: true,
    canAccessAuditLogs: false,
    canAccessExpenses: true,
    canEdit: true,
    canDelete: false,
    canManageRoles: false,
  },
  Admin: {
    canAccessInventory: true,
    canAccessRecipes: true,
    canAccessProduction: true,
    canAccessSales: true,
    canAccessAttendance: true,
    canAccessSalary: false,
    canAccessCostReport: true,
    canAccessAuditLogs: false,
    canAccessExpenses: true,
    canEdit: true,
    canDelete: false,
    canManageRoles: false,
  },
  Salesperson: {
    canAccessInventory: false,
    canAccessRecipes: false,
    canAccessProduction: false,
    canAccessSales: true,
    canAccessAttendance: true,
    canAccessSalary: false,
    canAccessCostReport: false,
    canAccessAuditLogs: false,
    canAccessExpenses: true,
    canEdit: true,
    canDelete: false,
    canManageRoles: false,
  },
  Visitor: {
    canAccessInventory: true,
    canAccessRecipes: true,
    canAccessProduction: true,
    canAccessSales: true,
    canAccessAttendance: false,
    canAccessSalary: false,
    canAccessCostReport: true,
    canAccessAuditLogs: false,
    canAccessExpenses: true,
    canEdit: false,
    canDelete: false,
    canManageRoles: false,
  },
};

export const DEFAULT_USERS = [
  {
    id: 'usr_ceo',
    username: 'ceo',
    name: 'Executive Officer',
    role: 'CEO' as const,
    email: 'ceo@aadiyart3.com',
    phone: '+91 9842100011',
  },
  {
    id: 'usr_manager',
    username: 'manager',
    name: 'Factory Operations Manager',
    role: 'Manager' as const,
    email: 'workfortamil@gmail.com',
    phone: '+91 9842100022',
  },
  {
    id: 'usr_salesperson',
    username: 'sales',
    name: 'Sales Executive',
    role: 'Salesperson' as const,
    email: 'sales@aadiyart3.com',
    phone: '+91 9842100055',
  },
  {
    id: 'usr_admin',
    username: 'admin',
    name: 'Inventory Admin',
    role: 'Admin' as const,
    email: 'admin@aadiyart3.com',
    phone: '+91 9842100033',
  },
  {
    id: 'usr_visitor',
    username: 'visitor',
    name: 'Auditor Visitor',
    role: 'Visitor' as const,
    email: 'visitor@aadiyart3.com',
    phone: '+91 9842100044',
  },
];

export const DEFAULT_COMPANY_SETTINGS: CompanyInvoiceSettings = {
  companyName: 'Aadiyar T3 Snacks',
  tagline: 'Fresh Wholesale & Retail Portion Snacks',
  address: '124 Factory Lane, Industrial Estate, Tamil Nadu',
  city: 'Madurai',
  state: 'Tamil Nadu',
  pincode: '625001',
  phone: '+91 9842100011',
  email: 'sales@aadiyart3.com',
  fssaiNumber: '12423008000456',
  gstin: '33ABCDE1234F1Z5',
  invoicePrefix: 'INV-',
  startingNumber: 1001,
  financialYear: '2026-2027',
  bankName: 'State Bank of India',
  accountNumber: '389201928301',
  ifscCode: 'SBIN0001234',
  branchName: 'Main Industrial Branch',
  upiId: 'aadiyart3@sbi',
  termsAndConditions: '1. Goods once sold will not be taken back.\n2. Interest @ 18% p.a. charged on overdue bills.',
  footerNote: 'Thank you for your business! Freshly fried with pure hygiene standards.',

  // Production Defaults
  defaultShift: 'Full Day',
  defaultOilType: 'Palm Oil',
  defaultOilCostPerLitre: 135,
  oilConsumptionBenchmarkRatio: 0.28,
  defaultFuelType: 'Firewood',
  defaultFirewoodCostPerKg: 8.5,
  defaultGasCostPerCylinder: 1850,
  defaultOverheadBurden: 300,
  autoDeductInventoryOnDailySave: true,
  lowStockThresholdKg: 10,
  currencySymbol: '₹',

  // Packaging Presets
  packagingPresets: [50, 100, 150, 200, 250, 400, 500, 1000, 5000],
  defaultPouchWastageBufferPercent: 3,

  // Labor Benchmarks
  defaultMasterDailyWage: 850,
  defaultHelperDailyWage: 550,
  defaultPackagingDailyWage: 600,
  defaultSalesmanDailyWage: 600,
  defaultOvertimeHourlyRate: 80,
  standardShiftHours: 8
};

export const DEFAULT_EMPLOYEES: EmployeeSalary[] = [];


export const INITIAL_DAILY_USAGE_ENTRIES: DailyUsageEntry[] = [];
